#!/bin/sh

mount -t proc proc /proc
mount -t tmpfs tmpfs /dev  -o size=64k,mode=0755
mkdir /dev/pts /dev/shm
mount -t devpts devpts /dev/pts
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs -osize=16M /tmp/ &
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s
