#!/bin/sh

PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin


mount |grep storage && {
  echo "storage mounted"
  exit;
}
echo "storage not mounted"
#flash_erase -j /dev/mtd8 0 0
#mount -t jffs2 /dev/mtdblock8  /storage

ubimkvol /dev/ubi0 -N storage -s 64MiB
VOL_NUM=`ubinfo /dev/ubi0 -N storage |grep Volume |sed -e 's/ /:/g' |sed -e 's/::/:/g' | sed -e 's/::/:/g'  |cut -d: -f3`
if [ "${NFSROOT}" != '' ]
then
      mkfs.ubifs /dev/ubi0_${VOL_NUM}
      mount -t ubifs ubi0:storage  /storage
fi
